"""
Offline invoice synchronization API.

Frontend:

    IndexedDB
        |
        v
    POST /api/sync/invoices
        |
        +-- existing client_uuid -> duplicate
        |
        +-- new client_uuid
                |
                v
          validate invoice
                |
                v
          restore product photo
                |
                v
          create Invoice
                |
                v
          create InvoiceItem[]
                |
                v
          generate PDF
                |
                v
          WhatsApp / SMS

Offline photo format:

    photo_base64
    photo_content_type

The client_uuid is the idempotency key.
"""

from __future__ import annotations

import base64
import binascii
import logging
import uuid
from datetime import datetime

from fastapi import (
    APIRouter,
    Depends,
)
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import Session

from app.database import get_db
from app.deps import get_current_agent
from app.models import Agent, Invoice
from app.schemas import (
    InvoiceCreate,
    InvoiceSyncRequest,
    InvoiceSyncResponse,
    SyncResultItem,
)
from app.services import storage
from app.services.invoice_service import (
    create_and_deliver,
)


logger = logging.getLogger(
    "sync"
)


# ============================================================
# ROUTER
# ============================================================

router = APIRouter(
    prefix="/api/sync",
    tags=["sync"],
)


# ============================================================
# CONSTANTS
# ============================================================

MAX_PHOTO_BYTES = (
    8 * 1024 * 1024
)


ALLOWED_CONTENT_TYPES = {
    "image/jpeg",
    "image/png",
    "image/webp",
    "image/heic",
}


# ============================================================
# HELPERS
# ============================================================


def _error_result(
    client_uuid: str,
    error: str,
) -> SyncResultItem:
    """
    Build a standard sync error response.
    """

    return SyncResultItem(
        client_uuid=client_uuid,
        status="error",
        error=error,
    )


def _duplicate_result(
    invoice: Invoice,
) -> SyncResultItem:
    """
    Build a duplicate response.

    Duplicate is considered successful from the frontend's
    perspective because the invoice already exists.
    """

    return SyncResultItem(
        client_uuid=invoice.client_uuid,
        status="duplicate",
        invoice_id=invoice.id,
        invoice_number=invoice.invoice_number,
    )


def _created_result(
    invoice: Invoice,
) -> SyncResultItem:
    """
    Build a successful creation response.
    """

    return SyncResultItem(
        client_uuid=invoice.client_uuid,
        status="created",
        invoice_id=invoice.id,
        invoice_number=invoice.invoice_number,
    )


def _validate_client_uuid(
    value: object,
) -> str:
    """
    Validate and normalize client_uuid.

    The database column allows 36 characters and the intended
    value is a UUID generated by the frontend.
    """

    client_uuid = str(
        value or ""
    ).strip()

    if not client_uuid:

        raise ValueError(
            "client_uuid is required."
        )

    if len(client_uuid) > 36:

        raise ValueError(
            "client_uuid must not exceed 36 characters."
        )

    # --------------------------------------------------------
    # Prefer actual UUID validation.
    # --------------------------------------------------------

    try:

        parsed = uuid.UUID(
            client_uuid
        )

        return str(
            parsed
        )

    except (
        ValueError,
        AttributeError,
    ):

        # ----------------------------------------------------
        # Existing frontend installations may use a
        # non-UUID 36-character idempotency value.
        # Keep supporting those values.
        # ----------------------------------------------------

        return client_uuid


def _decode_photo(
    photo_base64: str,
    content_type: str,
) -> bytes:
    """
    Decode the offline base64 photo.

    The frontend should store only the base64 payload,
    without:

        data:image/jpeg;base64,
    """

    if not photo_base64:

        raise ValueError(
            "Product photo is required."
        )

    content_type = (
        str(
            content_type
        )
        .strip()
        .lower()
    )

    if (
        content_type
        not in ALLOWED_CONTENT_TYPES
    ):

        raise ValueError(
            f"Unsupported photo type: {content_type}"
        )

    # --------------------------------------------------------
    # Protect server from excessively large base64 strings.
    # Base64 is approximately 4/3 of the binary size.
    # --------------------------------------------------------

    max_base64_length = (
        (MAX_PHOTO_BYTES * 4) // 3
    ) + 16

    if len(photo_base64) > max_base64_length:

        raise ValueError(
            "Photo exceeds 8MB limit."
        )

    try:

        photo_bytes = (
            base64.b64decode(
                photo_base64,
                validate=True,
            )
        )

    except (
        ValueError,
        binascii.Error,
    ) as exc:

        raise ValueError(
            "Invalid product photo data."
        ) from exc

    if not photo_bytes:

        raise ValueError(
            "Product photo is empty."
        )

    if len(photo_bytes) > MAX_PHOTO_BYTES:

        raise ValueError(
            "Photo exceeds 8MB limit."
        )

    return photo_bytes


def _photo_extension(
    content_type: str,
) -> str:
    """
    Return the correct extension for an allowed photo type.
    """

    extensions = {
        "image/jpeg": ".jpg",
        "image/png": ".png",
        "image/webp": ".webp",
        "image/heic": ".heic",
    }

    return extensions[
        content_type
    ]


def _save_offline_photo(
    photo_base64: str,
    photo_content_type: str | None,
) -> str:
    """
    Decode and save an offline product photo.

    Uses the normal storage abstraction so both local
    storage and S3-compatible storage work.
    """

    content_type = (
        str(
            photo_content_type
            or "image/jpeg"
        )
        .strip()
        .lower()
    )

    photo_bytes = _decode_photo(
        photo_base64=photo_base64,
        content_type=content_type,
    )

    filename = (
        f"{uuid.uuid4().hex}"
        f"{_photo_extension(content_type)}"
    )

    return storage.save_bytes(
        photo_bytes,
        "photos",
        filename,
    )


def _parse_captured_at(
    value: object,
) -> datetime:
    """
    Normalize captured_at.

    Invalid timestamps fall back to the current UTC time.
    """

    if value is None:

        return datetime.utcnow()

    if isinstance(
        value,
        datetime,
    ):

        return value

    try:

        return datetime.fromisoformat(
            str(value).replace(
                "Z",
                "+05:30",
            )
        )

    except ValueError:

        return datetime.utcnow()


# ============================================================
# PAYMENT MODE NORMALIZATION
# ============================================================


def _normalize_payment_mode(
    value: object,
) -> str:
    """
    Normalize payment mode received from an offline device.

    Accepted values:

        online
        cash

    Handles:

        None
        empty string
        normal strings
        uppercase strings
        whitespace
        Python Enum values
        PaymentMode.online
        PaymentMode.cash
        legacy IndexedDB values

    Unknown values are safely converted to "online".
    """

    # --------------------------------------------------------
    # Missing payment mode
    # --------------------------------------------------------

    if value is None:

        return "online"

    # --------------------------------------------------------
    # Python Enum
    #
    # PaymentMode.online
    # -> "online"
    #
    # PaymentMode.cash
    # -> "cash"
    # --------------------------------------------------------

    if hasattr(
        value,
        "value",
    ):

        value = value.value

    # --------------------------------------------------------
    # Convert to string and normalize.
    # --------------------------------------------------------

    normalized = str(
        value
    ).strip().lower()

    # --------------------------------------------------------
    # Handle:
    #
    # PaymentMode.online
    # PaymentMode.cash
    #
    # --------------------------------------------------------

    if "." in normalized:

        normalized = normalized.split(
            "."
        )[-1]

    # --------------------------------------------------------
    # Valid values
    # --------------------------------------------------------

    if normalized == "cash":

        return "cash"

    if normalized == "online":

        return "online"

    # --------------------------------------------------------
    # Unknown / legacy value.
    #
    # Do not break the entire offline queue.
    # Default to online.
    # --------------------------------------------------------

    logger.warning(
        "Invalid payment_mode received during offline sync: %r. "
        "Normalized value: %r. Defaulting to 'online'.",
        value,
        normalized,
    )

    return "online"


# ============================================================
# PREPARE OFFLINE INVOICE
# ============================================================


def _prepare_invoice_data(
    raw_invoice: dict,
) -> tuple[
    InvoiceCreate,
    str,
    str,
    str,
]:
    """
    Validate and normalize the offline invoice.

    Returns:

        invoice_data
        photo_base64
        photo_content_type
        client_uuid
    """

    # ========================================================
    # CLIENT UUID
    # ========================================================

    client_uuid = _validate_client_uuid(
        raw_invoice.get(
            "client_uuid"
        )
    )

    # ========================================================
    # PHOTO
    # ========================================================

    photo_base64 = str(
        raw_invoice.get(
            "photo_base64",
            "",
        )
    )

    photo_content_type = (
        str(
            raw_invoice.get(
                "photo_content_type",
                "image/jpeg",
            )
            or "image/jpeg"
        )
        .strip()
        .lower()
    )

    # --------------------------------------------------------
    # Validate photo now.
    # Do not save it until invoice validation succeeds.
    # --------------------------------------------------------

    _decode_photo(
        photo_base64=photo_base64,
        content_type=photo_content_type,
    )

    # ========================================================
    # COPY DATA
    # ========================================================

    data = dict(
        raw_invoice
    )

    # ========================================================
    # REMOVE OFFLINE-ONLY FIELDS
    # ========================================================

    data.pop(
        "photo_base64",
        None,
    )

    data.pop(
        "photo_content_type",
        None,
    )

    # ========================================================
    # NORMALIZE UUID
    # ========================================================

    data[
        "client_uuid"
    ] = client_uuid

    # ========================================================
    # NORMALIZE CAPTURED AT
    # ========================================================

    data[
        "captured_at"
    ] = _parse_captured_at(
        data.get(
            "captured_at"
        )
    )

    # ========================================================
    # NORMALIZE PAYMENT MODE
    # ========================================================

    data[
        "payment_mode"
    ] = _normalize_payment_mode(
        data.get(
            "payment_mode"
        )
    )

    logger.info(
        "Prepared offline invoice %s "
        "with payment_mode=%r",
        client_uuid,
        data[
            "payment_mode"
        ],
    )

    # ========================================================
    # PYDANTIC VALIDATION
    # ========================================================

    invoice_data = (
        InvoiceCreate.model_validate(
            data
        )
    )

    return (
        invoice_data,
        photo_base64,
        photo_content_type,
        client_uuid,
    )


# ============================================================
# SYNC INVOICES
# ============================================================


@router.post(
    "/invoices",
    response_model=InvoiceSyncResponse,
)
def sync_invoices(
    payload: InvoiceSyncRequest,
    db: Session = Depends(
        get_db
    ),
    agent: Agent = Depends(
        get_current_agent
    ),
) -> InvoiceSyncResponse:
    """
    Synchronize invoices stored in IndexedDB.

    Each invoice is processed independently.

    One bad invoice does not prevent the remaining invoices
    from synchronizing.
    """

    # ========================================================
    # EMPTY REQUEST
    # ========================================================

    if not payload.items:

        return InvoiceSyncResponse(
            results=[]
        )

    # ========================================================
    # RESULTS
    # ========================================================

    results: list[
        SyncResultItem
    ] = []

    # ========================================================
    # PROCESS EACH INVOICE
    # ========================================================

    for sync_item in payload.items:

        client_uuid = str(
            sync_item.client_uuid
        ).strip()

        try:

            # ==================================================
            # IDEMPOTENCY
            # ==================================================

            # client_uuid is globally UNIQUE in the database,
            # so do not scope this lookup to agent_id.

            existing = (
                db.query(Invoice)
                .filter(
                    Invoice.client_uuid
                    == client_uuid
                )
                .first()
            )

            if existing:

                results.append(
                    _duplicate_result(
                        existing
                    )
                )

                continue

            # ==================================================
            # PYDANTIC -> DICT
            # ==================================================

            raw_invoice = (
                sync_item.model_dump(
                    mode="python"
                )
            )

            # ==================================================
            # PHOTO DATA
            # ==================================================

            photo_base64 = raw_invoice.get(
                "photo_base64"
            )

            photo_content_type = (
                raw_invoice.get(
                    "photo_content_type"
                )
                or "image/jpeg"
            )

            if not photo_base64:

                results.append(
                    _error_result(
                        client_uuid=client_uuid,
                        error=(
                            "Product photo "
                            "is required."
                        ),
                    )
                )

                continue

            # ==================================================
            # VALIDATE + NORMALIZE INVOICE
            # ==================================================

            try:

                (
                    invoice_data,
                    photo_base64,
                    photo_content_type,
                    client_uuid,
                ) = _prepare_invoice_data(
                    raw_invoice
                )

            except ValueError as exc:

                db.rollback()

                results.append(
                    _error_result(
                        client_uuid=client_uuid,
                        error=str(exc),
                    )
                )

                continue

            except Exception as exc:

                db.rollback()

                logger.exception(
                    "Invoice validation failed "
                    "for %s",
                    client_uuid,
                )

                results.append(
                    _error_result(
                        client_uuid=client_uuid,
                        error=(
                            str(exc)
                            or "Invalid invoice data."
                        ),
                    )
                )

                continue

            # ==================================================
            # SAVE PHOTO
            # ==================================================

            try:

                photo_relative_path = (
                    _save_offline_photo(
                        photo_base64=(
                            photo_base64
                        ),
                        photo_content_type=(
                            photo_content_type
                        ),
                    )
                )

            except ValueError as exc:

                results.append(
                    _error_result(
                        client_uuid=client_uuid,
                        error=str(exc),
                    )
                )

                continue

            except Exception:

                db.rollback()

                logger.exception(
                    "Failed to restore "
                    "offline photo for %s",
                    client_uuid,
                )

                results.append(
                    _error_result(
                        client_uuid=client_uuid,
                        error=(
                            "Unable to save "
                            "product photo."
                        ),
                    )
                )

                continue

            # ==================================================
            # CREATE + DELIVER
            # ==================================================

            try:

                invoice = create_and_deliver(
                    db=db,
                    agent=agent,
                    data=(
                        invoice_data.model_dump(
                            mode="json"
                        )
                    ),
                    photo_relative_path=(
                        photo_relative_path
                    ),
                )

            except ValueError as exc:

                db.rollback()

                logger.exception(
                    "Validation failed while "
                    "creating synced invoice %s",
                    client_uuid,
                )

                results.append(
                    _error_result(
                        client_uuid=client_uuid,
                        error=str(exc),
                    )
                )

                continue

            # ==================================================
            # SUCCESS
            # ==================================================

            results.append(
                _created_result(
                    invoice
                )
            )

        # ====================================================
        # DATABASE INTEGRITY ERROR
        # ====================================================

        except IntegrityError:

            db.rollback()

            logger.exception(
                "Database integrity error "
                "while syncing invoice %s",
                client_uuid,
            )

            # ------------------------------------------------
            # Race-condition-safe duplicate check.
            #
            # Do NOT scope this to agent_id because
            # Invoice.client_uuid is globally unique.
            # ------------------------------------------------

            existing = (
                db.query(Invoice)
                .filter(
                    Invoice.client_uuid
                    == client_uuid
                )
                .first()
            )

            if existing:

                results.append(
                    _duplicate_result(
                        existing
                    )
                )

            else:

                results.append(
                    _error_result(
                        client_uuid=client_uuid,
                        error=(
                            "Database error while "
                            "creating invoice."
                        ),
                    )
                )

        # ====================================================
        # UNEXPECTED ERROR
        # ====================================================

        except Exception as exc:

            db.rollback()

            logger.exception(
                "Failed to sync invoice %s",
                client_uuid,
            )

            results.append(
                _error_result(
                    client_uuid=client_uuid,
                    error=(
                        str(exc)
                        or "Invoice synchronization failed."
                    ),
                )
            )

    # ========================================================
    # RESPONSE
    # ========================================================

    return InvoiceSyncResponse(
        results=results
    )